version: '3.8'

services:
  nexus-db:
    image: postgres:15-alpine
    container_name: nexus-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nexus_db
    ports:
      - "5432:5432"
    volumes:
      - nexus-db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  nexus-db-data: